//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BaseDeDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Equipment
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Equipment()
        {
            this.Components = new HashSet<Component>();
        }
    
        public int Id { get; set; }
        public Nullable<int> EquipmentTypeId { get; set; }
        public Nullable<int> ModelId { get; set; }
        public Nullable<int> BrandId { get; set; }
        public Nullable<int> StatusId { get; set; }
        public Nullable<int> WarehouseId { get; set; }
        public Nullable<System.DateTime> EntryDate { get; set; }
        public string Serie { get; set; }
        public string SofttekId { get; set; }
        public bool Active { get; set; }
    
        public virtual Brand Brand { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Component> Components { get; set; }
        public virtual EquipmentType EquipmentType { get; set; }
        public virtual Model Model { get; set; }
        public virtual Status Status { get; set; }
        public virtual Warehouse Warehouse { get; set; }
    }
}
